### ISSUE TITLE
[Question] Collaborating on issues in the Pivotal tracker

### ISSUE THREAD

**Issue by Phanatic** [cloudfoundry-attic/eclipse-integration-cloudfoundry#18]
Hi folks, 
I'd like to understand how I can communicate that I'm fixing issues that are filed in the Pivotal tracker. For example, I'm working on a fix for this issue [Add operation buttons to Env Variables wizard page.](https://www.pivotaltracker.com/n/projects/1027166/stories/60123062), and before I send out the PR, I'd like to communicate that I'm working on this issue and maybe get the issue assigned to me in the Pivotal tracker. Am looking for the workflow of working between the tracker and github issues.

**Comment by flavorjones** [comment]
Hi there!

We use Pivotal Tracker to provide visibility into what our team is working on. A story for this issue has been automatically created.

The current status is as follows:

* [ ] [#99824276](https://www.pivotaltracker.com/story/show/99824276) [Question] Collaborating on issues in the Pivotal tracker


This comment, as well as the labels on the issue, will be automatically updated as the status in Tracker changes.
