### ISSUE TITLE
Drag & Drop of web app opens the Deploy Application wizard twice

### ISSUE THREAD

**Issue by Phanatic** [cloudfoundry-attic/eclipse-integration-cloudfoundry#19]
When I drag and drop a web app onto the application & services window in a server's properties, the Deploy application wizard pops up twice.
The plugin version I'm using is :
Cloud Foundry Integration for Eclipse   1.7.0.201406182004-RELEASE  

Here's a screenshot
![img](https://s3.amazonaws.com/uploads.hipchat.com/8522/779588/6qdItbnLyiSUbTt/Screen%20Shot%202014-07-16%20at%208.59.41%20AM.png)

**Comment by flavorjones** [comment]
Hi there!

We use Pivotal Tracker to provide visibility into what our team is working on. A story for this issue has been automatically created.

The current status is as follows:

* [ ] [#99824274](https://www.pivotaltracker.com/story/show/99824274) Drag & Drop of web app opens the Deploy Application wizard twice


This comment, as well as the labels on the issue, will be automatically updated as the status in Tracker changes.
